### ISSUE TITLE
Cannot find wait.h on Mac

### ISSUE THREAD

**Issue by dristic** [fekberg/GoHttp#6]
When I try to compile the app I get an error saying "Cannot find file wait.h" when compiling on Mac OSX Mavericks.

To fix this, I had to change wait.h to sys/wait.h which allows it to compile correctly. I am not sure if this is just a Mac issue or not but I will leave it up to you to decide if you want to make the change!

**Comment by ColumPaget** [comment]
hmm, sys/wait.h compiles even though it's not in /usr/include/sys. It must be in one of the gcc include directories. This does mean I'll have to update *everything* that comes with a bundled libUseful!

thanks for reporting this. Does fileferry build if you make the change yourself?
